mode: 'development'
highlighter: true

# Switches off the asset bundler when developing
asset_bundler:
  dev: true

assets:
  debug: true
  cachebust: none
  cache: true
  sources:
    - ui/js
    - ui/less
    - ui/css
    - bower_components/jquery/dist/ 
    - bower_components/modernizr/
    - bower_components/bootstrap/dist/js/
    - bower_components/underscore/
    - bower_components/handlebars/
    - bower_components/backbone/
    - bower_components/layoutmanager/
    - bower_components/domready/
    - bower_components/bootstrap/dist/css/
    - bower_components/isotope/dist/
    - bower_components/showdown/compressed/
    - bower_components/jquery.lazyload/
  js_compressor: none
  css_compressor: none

image:
  source:
