source 'https://rubygems.org'
gem 'jekyll', '2.0.3'
gem 'RedCloth'
gem 'domainatrix'
gem 'kramdown'
gem 'yui-compressor'
gem 'jekyll-assets'
gem 'therubyracer'
gem 'less'
gem 'nokogiri'
gem 'json'
gem "mini_magick", '>=3.6'
gem 'ejs'
